name: coinjoin-analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment paths
      run: |
        echo "HOME: $HOME"
        echo "PWD: $(pwd)"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # change as needed

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Show pip version
      run: python -m pip -V

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Install project in editable mode
      run: python -m pip install -e .

    - name: Prepare test folder
      run: |
        export BTC_ROOT="$GITHUB_WORKSPACE/test_root"
        mkdir -p "$BTC_ROOT"
        cp -r . "$BTC_ROOT"
        cp coinjoin-analysis/tests/fixtures/dumplings__end_zksnacks_202505.zip "$BTC_ROOT/dumplings.zip"

    - name: Run tests
      run: |
        python -m pip install pytest  # or your test framework
        pytest  # or whatever command you use