name: coinjoin-analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment paths
      run: |
        echo "HOME: $HOME"
        echo "PWD: $(pwd)"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # change as needed

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Show pip version
      run: python -m pip -V

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Install project in editable mode
      run: python -m pip install -e .

    - name: Install Graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Run tests
      run: |
        python -m pip install pytest  
        pytest  

    - name: Show directory structure with tree
      if: always()
      run: |
        tree -a -L 5 ../temp_dumplings || echo "Directory not found" 