name: coinjoin-analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # change as needed

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Show pip version
      run: python -m pip -V

    - name: Install project in editable mode
      run: python -m pip install -e .

    - name: Run tests
      run: |
        python -m pip install pytest  # or your test framework
        pytest  # or whatever command you use